# Generated by Django 3.1.3 on 2020-11-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(default='', max_length=30)),
                ('disease_description', models.CharField(default='', max_length=500)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fit.doctors')),
                ('pat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fit.patient')),
            ],
        ),
    ]
