# Generated by Django 3.1.3 on 2020-11-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0003_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='med1',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='disease',
            name='med2',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='disease',
            name='med3',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='disease',
            name='med4',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='disease',
            name='med5',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='disease',
            name='med6',
            field=models.CharField(default='', max_length=60),
        ),
    ]
