# Generated by Django 3.1.3 on 2020-11-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_auto_20201123_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='med1',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='disease',
            name='med2',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='disease',
            name='med3',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='disease',
            name='med4',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='disease',
            name='med5',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='disease',
            name='med6',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
