# Generated by Django 3.1.3 on 2020-11-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0007_auto_20201124_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pat_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
