# Generated by Django 3.1.3 on 2020-11-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0008_patient_pat_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmay_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
