# Generated by Django 3.1.3 on 2020-11-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0009_auto_20201124_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='phar_email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
