# Generated by Django 3.1.3 on 2020-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0010_auto_20201124_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_address',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_category',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_email',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_idProof',
            field=models.ImageField(default='', null=True, upload_to='fit/doctors'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_location',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doc_username',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_address',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_email',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_loc',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_username',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
