# Generated by Django 3.1.3 on 2020-11-26 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0012_auto_20201124_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_date', models.DateField()),
                ('appoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fit.doctors')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fit.patient')),
            ],
        ),
    ]
